spring:
  application:
    name: rag

# 向量数据库相关配置 (对应 QdrantProperties 类)
qdrant:
  host: localhost
  port: 6334
  collection: rag_test_collection

# RAG 文档切分参数配置 (对应 RagDocumentProperties 类)
rag:
  document:
    max-segment-size: 300 # 每个切片的最大字数
    max-overlap-size: 30  # 相邻切片重叠的字数

# 大语言模型配置 (通义千问)
dashscope:
  api-key: ""
  model-name: qwen-plus

# 重排模型配置 (Cohere)
cohere:
  api-key: ""
  model-name: rerank-multilingual-v3.0